// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_log (transaction_id, user_id, event_type, old_state, new_state, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at
`

type CreateAuditLogParams struct {
	TransactionID pgtype.UUID          `json:"transaction_id"`
	UserID        pgtype.UUID          `json:"user_id"`
	EventType     string               `json:"event_type"`
	OldState      NullTransactionState `json:"old_state"`
	NewState      NullTransactionState `json:"new_state"`
	Metadata      []byte               `json:"metadata"`
}

type CreateAuditLogRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (CreateAuditLogRow, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.TransactionID,
		arg.UserID,
		arg.EventType,
		arg.OldState,
		arg.NewState,
		arg.Metadata,
	)
	var i CreateAuditLogRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listAuditLogByTransaction = `-- name: ListAuditLogByTransaction :many
SELECT id, transaction_id, user_id, event_type, old_state, new_state, metadata, created_at
FROM audit_log
WHERE transaction_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAuditLogByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.UserID,
			&i.EventType,
			&i.OldState,
			&i.NewState,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByUser = `-- name: ListAuditLogByUser :many
SELECT id, transaction_id, event_type, old_state, new_state, metadata, created_at
FROM audit_log
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListAuditLogByUserRow struct {
	ID            int64                `json:"id"`
	TransactionID pgtype.UUID          `json:"transaction_id"`
	EventType     string               `json:"event_type"`
	OldState      NullTransactionState `json:"old_state"`
	NewState      NullTransactionState `json:"new_state"`
	Metadata      []byte               `json:"metadata"`
	CreatedAt     pgtype.Timestamptz   `json:"created_at"`
}

func (q *Queries) ListAuditLogByUser(ctx context.Context, arg ListAuditLogByUserParams) ([]ListAuditLogByUserRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogByUserRow
	for rows.Next() {
		var i ListAuditLogByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.EventType,
			&i.OldState,
			&i.NewState,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
