// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type TransactionState string

const (
	TransactionStatePending       TransactionState = "pending"
	TransactionStateFiatReceived  TransactionState = "fiat_received"
	TransactionStateAmlChecking   TransactionState = "aml_checking"
	TransactionStateAmlPassed     TransactionState = "aml_passed"
	TransactionStateSwapping      TransactionState = "swapping"
	TransactionStateSwapComplete  TransactionState = "swap_complete"
	TransactionStateCompleted     TransactionState = "completed"
	TransactionStateFailed        TransactionState = "failed"
	TransactionStateRefundPending TransactionState = "refund_pending"
	TransactionStateRefunded      TransactionState = "refunded"
)

func (e *TransactionState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionState(s)
	case string:
		*e = TransactionState(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionState: %T", src)
	}
	return nil
}

type NullTransactionState struct {
	TransactionState TransactionState `json:"transaction_state"`
	Valid            bool             `json:"valid"` // Valid is true if TransactionState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionState) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionState), nil
}

type UserStatus string

const (
	UserStatusActive      UserStatus = "active"
	UserStatusSuspended   UserStatus = "suspended"
	UserStatusKycRequired UserStatus = "kyc_required"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuditLog struct {
	ID            int64                `json:"id"`
	TransactionID pgtype.UUID          `json:"transaction_id"`
	UserID        pgtype.UUID          `json:"user_id"`
	EventType     string               `json:"event_type"`
	OldState      NullTransactionState `json:"old_state"`
	NewState      NullTransactionState `json:"new_state"`
	Metadata      []byte               `json:"metadata"`
	CreatedAt     pgtype.Timestamptz   `json:"created_at"`
}

type Transaction struct {
	ID               pgtype.UUID          `json:"id"`
	UserID           pgtype.UUID          `json:"user_id"`
	FiatAmountCents  int64                `json:"fiat_amount_cents"`
	FiatCurrency     pgtype.Text          `json:"fiat_currency"`
	CryptoAmountUsdc pgtype.Numeric       `json:"crypto_amount_usdc"`
	State            NullTransactionState `json:"state"`
	CardPaymentID    pgtype.Text          `json:"card_payment_id"`
	BlockradarSwapID pgtype.Text          `json:"blockradar_swap_id"`
	BlockchainTxHash pgtype.Text          `json:"blockchain_tx_hash"`
	InitiatedAt      pgtype.Timestamptz   `json:"initiated_at"`
	FiatReceivedAt   pgtype.Timestamptz   `json:"fiat_received_at"`
	AmlCompletedAt   pgtype.Timestamptz   `json:"aml_completed_at"`
	SwapCompletedAt  pgtype.Timestamptz   `json:"swap_completed_at"`
	CompletedAt      pgtype.Timestamptz   `json:"completed_at"`
	FailedAt         pgtype.Timestamptz   `json:"failed_at"`
	FailureReason    pgtype.Text          `json:"failure_reason"`
	ClientIp         *netip.Addr          `json:"client_ip"`
	UserAgent        pgtype.Text          `json:"user_agent"`
	IdempotencyKey   pgtype.Text          `json:"idempotency_key"`
	CreatedAt        pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz   `json:"updated_at"`
}

type User struct {
	ID                           pgtype.UUID        `json:"id"`
	GoogleID                     pgtype.Text        `json:"google_id"`
	Email                        string             `json:"email"`
	Password                     pgtype.Text        `json:"password"`
	BlockradarChildWalletAddress pgtype.Text        `json:"blockradar_child_wallet_address"`
	WalletAddress                pgtype.Text        `json:"wallet_address"`
	UserStatus                   NullUserStatus     `json:"user_status"`
	KycVerified                  pgtype.Bool        `json:"kyc_verified"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt                  pgtype.Timestamptz `json:"last_login_at"`
}
