// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (CreateAuditLogRow, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetPendingTransactions(ctx context.Context) ([]GetPendingTransactionsRow, error)
	GetTransactionByID(ctx context.Context, id pgtype.UUID) (GetTransactionByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (GetUserByGoogleIDRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListAuditLogByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]AuditLog, error)
	ListAuditLogByUser(ctx context.Context, arg ListAuditLogByUserParams) ([]ListAuditLogByUserRow, error)
	ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]ListTransactionsByUserRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateTransactionAMLPassed(ctx context.Context, id pgtype.UUID) error
	UpdateTransactionCompleted(ctx context.Context, arg UpdateTransactionCompletedParams) error
	UpdateTransactionFailed(ctx context.Context, arg UpdateTransactionFailedParams) error
	UpdateTransactionFiatReceived(ctx context.Context, arg UpdateTransactionFiatReceivedParams) error
	UpdateTransactionState(ctx context.Context, arg UpdateTransactionStateParams) error
	UpdateTransactionSwapping(ctx context.Context, arg UpdateTransactionSwappingParams) error
	UpdateUserGoogleID(ctx context.Context, arg UpdateUserGoogleIDParams) error
	UpdateUserWallet(ctx context.Context, arg UpdateUserWalletParams) error
}

var _ Querier = (*Queries)(nil)
