// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, fiat_amount_cents, fiat_currency, state, client_ip, user_agent, idempotency_key)
VALUES ($1, $2, $3, 'pending', $4, $5, $6)
RETURNING id, user_id, fiat_amount_cents, fiat_currency, crypto_amount_usdc, state, blockchain_tx_hash, created_at
`

type CreateTransactionParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	FiatAmountCents int64       `json:"fiat_amount_cents"`
	FiatCurrency    pgtype.Text `json:"fiat_currency"`
	ClientIp        *netip.Addr `json:"client_ip"`
	UserAgent       pgtype.Text `json:"user_agent"`
	IdempotencyKey  pgtype.Text `json:"idempotency_key"`
}

type CreateTransactionRow struct {
	ID               pgtype.UUID          `json:"id"`
	UserID           pgtype.UUID          `json:"user_id"`
	FiatAmountCents  int64                `json:"fiat_amount_cents"`
	FiatCurrency     pgtype.Text          `json:"fiat_currency"`
	CryptoAmountUsdc pgtype.Numeric       `json:"crypto_amount_usdc"`
	State            NullTransactionState `json:"state"`
	BlockchainTxHash pgtype.Text          `json:"blockchain_tx_hash"`
	CreatedAt        pgtype.Timestamptz   `json:"created_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.FiatAmountCents,
		arg.FiatCurrency,
		arg.ClientIp,
		arg.UserAgent,
		arg.IdempotencyKey,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FiatAmountCents,
		&i.FiatCurrency,
		&i.CryptoAmountUsdc,
		&i.State,
		&i.BlockchainTxHash,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingTransactions = `-- name: GetPendingTransactions :many
SELECT id, user_id, fiat_amount_cents, fiat_currency, state, card_payment_id, blockradar_swap_id, created_at
FROM transactions
WHERE state IN ('pending', 'fiat_received', 'aml_checking', 'aml_passed', 'swapping')
ORDER BY created_at ASC
`

type GetPendingTransactionsRow struct {
	ID               pgtype.UUID          `json:"id"`
	UserID           pgtype.UUID          `json:"user_id"`
	FiatAmountCents  int64                `json:"fiat_amount_cents"`
	FiatCurrency     pgtype.Text          `json:"fiat_currency"`
	State            NullTransactionState `json:"state"`
	CardPaymentID    pgtype.Text          `json:"card_payment_id"`
	BlockradarSwapID pgtype.Text          `json:"blockradar_swap_id"`
	CreatedAt        pgtype.Timestamptz   `json:"created_at"`
}

func (q *Queries) GetPendingTransactions(ctx context.Context) ([]GetPendingTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getPendingTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingTransactionsRow
	for rows.Next() {
		var i GetPendingTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FiatAmountCents,
			&i.FiatCurrency,
			&i.State,
			&i.CardPaymentID,
			&i.BlockradarSwapID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, fiat_amount_cents, fiat_currency, crypto_amount_usdc, state,
       card_payment_id, blockradar_swap_id, blockchain_tx_hash,
       initiated_at, fiat_received_at, aml_completed_at, swap_completed_at, completed_at, failed_at,
       failure_reason, created_at, updated_at
FROM transactions
WHERE id = $1
`

type GetTransactionByIDRow struct {
	ID               pgtype.UUID          `json:"id"`
	UserID           pgtype.UUID          `json:"user_id"`
	FiatAmountCents  int64                `json:"fiat_amount_cents"`
	FiatCurrency     pgtype.Text          `json:"fiat_currency"`
	CryptoAmountUsdc pgtype.Numeric       `json:"crypto_amount_usdc"`
	State            NullTransactionState `json:"state"`
	CardPaymentID    pgtype.Text          `json:"card_payment_id"`
	BlockradarSwapID pgtype.Text          `json:"blockradar_swap_id"`
	BlockchainTxHash pgtype.Text          `json:"blockchain_tx_hash"`
	InitiatedAt      pgtype.Timestamptz   `json:"initiated_at"`
	FiatReceivedAt   pgtype.Timestamptz   `json:"fiat_received_at"`
	AmlCompletedAt   pgtype.Timestamptz   `json:"aml_completed_at"`
	SwapCompletedAt  pgtype.Timestamptz   `json:"swap_completed_at"`
	CompletedAt      pgtype.Timestamptz   `json:"completed_at"`
	FailedAt         pgtype.Timestamptz   `json:"failed_at"`
	FailureReason    pgtype.Text          `json:"failure_reason"`
	CreatedAt        pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz   `json:"updated_at"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FiatAmountCents,
		&i.FiatCurrency,
		&i.CryptoAmountUsdc,
		&i.State,
		&i.CardPaymentID,
		&i.BlockradarSwapID,
		&i.BlockchainTxHash,
		&i.InitiatedAt,
		&i.FiatReceivedAt,
		&i.AmlCompletedAt,
		&i.SwapCompletedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT id, fiat_amount_cents, fiat_currency, crypto_amount_usdc, state, blockchain_tx_hash, created_at
FROM transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListTransactionsByUserRow struct {
	ID               pgtype.UUID          `json:"id"`
	FiatAmountCents  int64                `json:"fiat_amount_cents"`
	FiatCurrency     pgtype.Text          `json:"fiat_currency"`
	CryptoAmountUsdc pgtype.Numeric       `json:"crypto_amount_usdc"`
	State            NullTransactionState `json:"state"`
	BlockchainTxHash pgtype.Text          `json:"blockchain_tx_hash"`
	CreatedAt        pgtype.Timestamptz   `json:"created_at"`
}

func (q *Queries) ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]ListTransactionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByUserRow
	for rows.Next() {
		var i ListTransactionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FiatAmountCents,
			&i.FiatCurrency,
			&i.CryptoAmountUsdc,
			&i.State,
			&i.BlockchainTxHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionAMLPassed = `-- name: UpdateTransactionAMLPassed :exec
UPDATE transactions
SET state = 'aml_passed', aml_completed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateTransactionAMLPassed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateTransactionAMLPassed, id)
	return err
}

const updateTransactionCompleted = `-- name: UpdateTransactionCompleted :exec
UPDATE transactions
SET state = 'completed', crypto_amount_usdc = $2, blockchain_tx_hash = $3, completed_at = NOW(), swap_completed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type UpdateTransactionCompletedParams struct {
	ID               pgtype.UUID    `json:"id"`
	CryptoAmountUsdc pgtype.Numeric `json:"crypto_amount_usdc"`
	BlockchainTxHash pgtype.Text    `json:"blockchain_tx_hash"`
}

func (q *Queries) UpdateTransactionCompleted(ctx context.Context, arg UpdateTransactionCompletedParams) error {
	_, err := q.db.Exec(ctx, updateTransactionCompleted, arg.ID, arg.CryptoAmountUsdc, arg.BlockchainTxHash)
	return err
}

const updateTransactionFailed = `-- name: UpdateTransactionFailed :exec
UPDATE transactions
SET state = 'failed', failure_reason = $2, failed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type UpdateTransactionFailedParams struct {
	ID            pgtype.UUID `json:"id"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

func (q *Queries) UpdateTransactionFailed(ctx context.Context, arg UpdateTransactionFailedParams) error {
	_, err := q.db.Exec(ctx, updateTransactionFailed, arg.ID, arg.FailureReason)
	return err
}

const updateTransactionFiatReceived = `-- name: UpdateTransactionFiatReceived :exec
UPDATE transactions
SET state = 'fiat_received', card_payment_id = $2, fiat_received_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type UpdateTransactionFiatReceivedParams struct {
	ID            pgtype.UUID `json:"id"`
	CardPaymentID pgtype.Text `json:"card_payment_id"`
}

func (q *Queries) UpdateTransactionFiatReceived(ctx context.Context, arg UpdateTransactionFiatReceivedParams) error {
	_, err := q.db.Exec(ctx, updateTransactionFiatReceived, arg.ID, arg.CardPaymentID)
	return err
}

const updateTransactionState = `-- name: UpdateTransactionState :exec
UPDATE transactions
SET state = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTransactionStateParams struct {
	ID    pgtype.UUID          `json:"id"`
	State NullTransactionState `json:"state"`
}

func (q *Queries) UpdateTransactionState(ctx context.Context, arg UpdateTransactionStateParams) error {
	_, err := q.db.Exec(ctx, updateTransactionState, arg.ID, arg.State)
	return err
}

const updateTransactionSwapping = `-- name: UpdateTransactionSwapping :exec
UPDATE transactions
SET state = 'swapping', blockradar_swap_id = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTransactionSwappingParams struct {
	ID               pgtype.UUID `json:"id"`
	BlockradarSwapID pgtype.Text `json:"blockradar_swap_id"`
}

func (q *Queries) UpdateTransactionSwapping(ctx context.Context, arg UpdateTransactionSwappingParams) error {
	_, err := q.db.Exec(ctx, updateTransactionSwapping, arg.ID, arg.BlockradarSwapID)
	return err
}
