// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
RETURNING id, email, password, wallet_address, blockradar_child_wallet_address, user_status, kyc_verified, created_at, updated_at
`

type CreateUserParams struct {
	Email    string      `json:"email"`
	Password pgtype.Text `json:"password"`
}

type CreateUserRow struct {
	ID                           pgtype.UUID        `json:"id"`
	Email                        string             `json:"email"`
	Password                     pgtype.Text        `json:"password"`
	WalletAddress                pgtype.Text        `json:"wallet_address"`
	BlockradarChildWalletAddress pgtype.Text        `json:"blockradar_child_wallet_address"`
	UserStatus                   NullUserStatus     `json:"user_status"`
	KycVerified                  pgtype.Bool        `json:"kyc_verified"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.WalletAddress,
		&i.BlockradarChildWalletAddress,
		&i.UserStatus,
		&i.KycVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, wallet_address, blockradar_child_wallet_address, user_status, kyc_verified, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                           pgtype.UUID        `json:"id"`
	Email                        string             `json:"email"`
	Password                     pgtype.Text        `json:"password"`
	WalletAddress                pgtype.Text        `json:"wallet_address"`
	BlockradarChildWalletAddress pgtype.Text        `json:"blockradar_child_wallet_address"`
	UserStatus                   NullUserStatus     `json:"user_status"`
	KycVerified                  pgtype.Bool        `json:"kyc_verified"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.WalletAddress,
		&i.BlockradarChildWalletAddress,
		&i.UserStatus,
		&i.KycVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, password, wallet_address, blockradar_child_wallet_address, user_status, kyc_verified, created_at, updated_at
FROM users
WHERE google_id = $1
`

type GetUserByGoogleIDRow struct {
	ID                           pgtype.UUID        `json:"id"`
	Email                        string             `json:"email"`
	Password                     pgtype.Text        `json:"password"`
	WalletAddress                pgtype.Text        `json:"wallet_address"`
	BlockradarChildWalletAddress pgtype.Text        `json:"blockradar_child_wallet_address"`
	UserStatus                   NullUserStatus     `json:"user_status"`
	KycVerified                  pgtype.Bool        `json:"kyc_verified"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (GetUserByGoogleIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i GetUserByGoogleIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.WalletAddress,
		&i.BlockradarChildWalletAddress,
		&i.UserStatus,
		&i.KycVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, wallet_address, blockradar_child_wallet_address, user_status, kyc_verified, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID                           pgtype.UUID        `json:"id"`
	Email                        string             `json:"email"`
	Password                     pgtype.Text        `json:"password"`
	WalletAddress                pgtype.Text        `json:"wallet_address"`
	BlockradarChildWalletAddress pgtype.Text        `json:"blockradar_child_wallet_address"`
	UserStatus                   NullUserStatus     `json:"user_status"`
	KycVerified                  pgtype.Bool        `json:"kyc_verified"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.WalletAddress,
		&i.BlockradarChildWalletAddress,
		&i.UserStatus,
		&i.KycVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, wallet_address, user_status, kyc_verified, created_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	WalletAddress pgtype.Text        `json:"wallet_address"`
	UserStatus    NullUserStatus     `json:"user_status"`
	KycVerified   pgtype.Bool        `json:"kyc_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.WalletAddress,
			&i.UserStatus,
			&i.KycVerified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUserGoogleID = `-- name: UpdateUserGoogleID :exec
UPDATE users
SET google_id = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserGoogleIDParams struct {
	ID       pgtype.UUID `json:"id"`
	GoogleID pgtype.Text `json:"google_id"`
}

func (q *Queries) UpdateUserGoogleID(ctx context.Context, arg UpdateUserGoogleIDParams) error {
	_, err := q.db.Exec(ctx, updateUserGoogleID, arg.ID, arg.GoogleID)
	return err
}

const updateUserWallet = `-- name: UpdateUserWallet :exec
UPDATE users
SET wallet_address = $2, blockradar_child_wallet_address = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserWalletParams struct {
	ID            pgtype.UUID `json:"id"`
	WalletAddress pgtype.Text `json:"wallet_address"`
}

func (q *Queries) UpdateUserWallet(ctx context.Context, arg UpdateUserWalletParams) error {
	_, err := q.db.Exec(ctx, updateUserWallet, arg.ID, arg.WalletAddress)
	return err
}
